version: '3'
services: 
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      MSSQL_PID: "Express"
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pa55word123!"
    ports:
      - "1433:1433"
    volumes:
      - ./Data:/var/opt/mssql/data
      
  customersapi:
    image: cheranga/customersapi:v1.0.0  
    build: .
    environment:      
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 8081
      ASPNETCORE_ENVIRONMENT: "Development"
      DatabaseConfig:ServerName: "sqlserver"      
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    ports:
      - "8080:80"
      - "8081:443"